name: Build and Distribute

on:
    push:
        branches:
            - release
    pull_request:
        branches:
            - release

jobs:
    build:
        runs-on: windows-latest

        steps:
            # Step 1: Checkout il repository
            - name: Checkout Code
              uses: actions/checkout@v3

            # Step 2: Configura Python
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.10

            # Step 3: Verifica la versione di Python
            - name: Verify Python Version
              run: python --version

            # Step 4: Installa le dipendenze
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # Step 5: Build dell'eseguibile con PyInstaller
            - name: Build Executable
              run: |
                  pyinstaller main.spec --noconfirm

            # Step 6: Archivia i file per la distribuzione
            - name: Archive Build Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: built-executable
                  path: dist/
